---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-service-config
data:
  DATASOURCE_URL: "jdbc:postgresql://my_custom_server:5432/parodos"
  DATASOURCE_DRIVER: "org.postgresql.Driver"
  DATASOURCE_USERNAME: "parodos"
  DATASOURCE_PASSWORD: "parodos"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  DATASOURCE_URL: "jdbc:postgresql://my_custom_server:5432/parodos"
  DATASOURCE_DRIVER: "org.postgresql.Driver"
  DATASOURCE_USERNAME: "parodos"
  DATASOURCE_PASSWORD: "parodos"
